import "./globals.css";
import { Providers } from "./mantineProviders";
import { AuthProvider } from "@/components/Auth/AuthProvider";
import { supabase } from "@/utils/superbase-server";
import HomeNavBar from "@/(composition)/header/page";
import DashBoard from "@/(composition)/dashBoard";

export const metadata = {
  title: "viva presentation platform",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html lang="en">
      <body
      //  className={inter.className}
      >
        <AuthProvider accessToken={accessToken}>
          <Providers>
            <HomeNavBar />
            <DashBoard>{children}</DashBoard>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
